cnr.sh: add download_or_noop function
app-registry/helm-plugin pull request #22
Opened 2017-05-25 19:42 UTC by jzelinskie

This should cause the first attempt to use the registry plugin to
download the latest binary for the current platform.

This doesn't work on Windows, yet.

2017-05-25 20:31 UTC, ant31 requested changes

2017-05-25 20:31 UTC, ant31 commented on cnr.sh
> +  if [ ! -e "$HELM_PLUGIN_DIR/cnr" ]; then
I would show an error about that file missing, ask for download and then exit 1

```
$ helm registry list quay.io
Error: Appr client is missing: $HELM_HOME/plugins/registry/cnr
Do you want to install it ? yes
downloading from: '$URL'
$ echo $?
1
$ helm registry list quay.io
quay.io/ant31/ghost 
quay.io/charts/gitlab

```

2017-05-26 15:36 UTC, jzelinskie commented on cnr.sh
> +  if [ ! -e "$HELM_PLUGIN_DIR/cnr" ]; then
I think it's really confusing for someone to run `helm plug install github.com/app-registry/helm-plugin` and then immediately get prompted the first time they try to use it that they didn't actually install it.

2017-05-26 16:18 UTC, ant31 commented on cnr.sh
> +  if [ ! -e "$HELM_PLUGIN_DIR/cnr" ]; then
Yes, you can rephrase, this was just an example. 
Idea is to explain that something is missing rather than silently download it.

2017-05-30 17:01 UTC, ant31 approved these changes

2017-05-30 17:01 UTC, merged